version: '3.5'
services:
  web:
    build:
      context: .
      args:
        API_PORT: ${API_PORT}
        REACT_APP_PORT: ${REACT_APP_PORT}
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      API_PORT: ${API_PORT}
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped

