version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: testcontainer
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_PORT: ${PORT}
      REACT_APP_PORT: ${REACT_APP_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
